USE musicdb;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
	name VARCHAR(40) NOT NULL,
	email VARCHAR(50) NOT NULL,
	password VARCHAR(100) NOT NULL,
	admin TINYINT(1) NOT NULL,
	PRIMARY KEY(email)
);
